routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'PostController@index')->name('home');

Auth::routes();

Route::resource('users', 'UserController')
->only(['index', 'edit', 'update', 'show', 'destroy']);

Route::get('/{any}', 'PostController@index')->where('any', '.*');

Route::resource('posts', 'PostController')
    ->only(['index', 'create', 'show', 'destroy']);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'author_id', 'body'
    ];

    public function author()
    {
        return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts() {
        return $this->hasMany('App\Post', 'author_id');
    }
}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\CreatePostRequest;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Post;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    public function index() {
        $posts = Post::with('author:id,username,name')->orderBy('created_at', 'DESC')->paginate(5);
        return response()->json($posts);
    }

    public function create(Request $request) {
        Post::create([
            'author_id' => $request->user()->id,
            'body' => $request->input('body')
        ]);
        return response('OK', 200)
                          ->header('Content-Type', 'text/plain');;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::paginate(15);
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\Http\Requests\UpdateUserRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(20);
        return view('users.index', compact('users'));
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if (Auth::id() != $user->id) {
            abort(403);
        }
        return view('users.edit')->withUser($user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $user->update($request->all());
        return redirect()->route('users.show', ['id' => $user->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        abort(404);
    }
}

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>milliblog</title>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Caption" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/master.css">
</head>
<body>
    <div id="app">
        <div id="mainHeaderWrapper">
            <header id="mainHeader" class="container">
                <h1><a href="{{ route('home') }}"><i class="fas fa-cookie"></i> milliblog</a></h1>
                <div class="fg1"></div>
                @if(Auth::check())
                    <a href="{{ route('logout') }}" class="red button" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i class="fas fa-sign-out-alt"></i> Logout
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                @else
                    <a href="{{ route('register') }}" class="green button">Sign Up</a>
                    <a href="{{ route('login') }}" class="button"><i class="fas fa-sign-in-alt"></i> Sign In</a>
                @endif
            </header>
        </div>
        <div id="main">
            <div class="fg1"></div>
            <nav class="panel">
            </nav>
            @yield('content')
            <nav class="panel">
                <a href="{{ route('users.index') }}">Users</a>
            </nav>
            <div class="fg1"></div>
        </div>
        <footer id="mainFooter" class="container">
            <p>powered by milliblog microblogging engine</p>
        </footer>
    </div>
    <script src="{{ mix('js/app.js') }}"></script>
</body>
</html>

resources/views/partials/pagination.blade.php
@if ($paginator->hasPages())

    <nav class="pagination">
        @if ($paginator->onFirstPage())
            <a class="disabled">← Previous</a>
        @else
            <a href="{{ $paginator->previousPageUrl() }}" rel="prev">← Previous</a>
        @endif

        @foreach ($elements as $element)

            @if (is_string($element))
                <a class="disabled">{{ $element }}></a>
            @endif

            @if (is_array($element))

                @foreach ($element as $page => $url)

                    @if ($page == $paginator->currentPage())

                        <a class="disabled">{{ $page }}</li>

                    @else

                        <a href="{{ $url }}">{{ $page }}</a>

                    @endif

                @endforeach

            @endif

        @endforeach

        @if ($paginator->hasMorePages())

            <a href="{{ $paginator->nextPageUrl() }}" rel="next">Next →</a>

        @else

            <a class="disabled">Next →</a>

        @endif

    </nav>

@endif

resources/views/partials/posts.blade.php
@foreach ($posts as $post)
    <post id="{{ $post->id }}"></post>
@endforeach

resources/views/posts/index.blade.php
@extends('layout')

@section('content')
    <router-view></router-view>
    <post-list></post-list>
@endsection

resources/views/users/edit.blade.php
@extends('layout')

@section('content')
    <section class="container">
        <h1 class="title">My profile</a></h1>
        <form action="{{ route('users.update', ['id' => $user->id]) }}" method="post">
            @csrf
            @method('patch')
            <div class="field">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" value="{{ old('username', $user->username) }}">
                @if ($errors->has('username'))
                    <div class="error" role="alert">
                        {{ $errors->first('username') }}
                    </div>
                @endif
            </div>
            <div class="field">
                <label for="name">Display username</label>
                <input type="text" id="name" name="name" value="{{ old('name', $user->name) }}">
                @if ($errors->has('name'))
                    <div class="error" role="alert">
                        {{ $errors->first('name') }}
                    </div>
                @endif
            </div>
            <div class="field">
                <label for="email">Email address</label>
                <input type="email" id="email" name="email" value="{{ old('email', $user->email) }}">
                @if ($errors->has('email'))
                    <div class="error" role="alert">
                        {{ $errors->first('email') }}
                    </div>
                @endif
            </div>
            <button class="button" type="submit">Save</button>
        </form>
    </section>

@endsection

resources/views/users/index.blade.php
@extends('layout')

@section('content')
    <section class="container">
        <h1 class="title">Users</h1>
        <div class="users">
            @foreach($users as $user)
                <a href="{{ route('users.show', ['id' => $user->id]) }}" class="user">
                    <span>{{ $user->name }}</span>
                    <span class="at">{{ '@' . $user->username }}</span>
                </a>
            @endforeach
        </div>
        {{ $users->links('partials.pagination') }}
    </section>

@endsection

resources/views/users/show.blade.php
@extends('layout')

@section('content')
    <section class="container">
        <h1 class="title">{{ $user->name }} <a href="{{ route('users.show', $user->id) }}" class="at">{{ '@' . $user->username }}</a></h1>
        @if(Auth::id() == $user->id)
            <div class="button-group">
                <a href="{{ route('users.edit', ['id' => $user->id]) }}" class="green button">Edit</a>
            </div>
        @endif
        @include('partials.posts', ['posts' => $user->posts])
    </section>

@endsection